okta:
  oauth2:
    client-secret: m81BelJOLCO40dtyLoPfNF_RqAD2pLha1R5VIvCX
    client-id: 0oa4n8f92lCiUL4mr5d7
    issuer: https://dev-45372882.okta.com/oauth2/default
    redirect-uri: /login/oauth2/code/okta

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
      httpclient:
        ssl:
          useInsecureTrustManager: true
    routes:
        # TODO - solve service names
      - id: bank
        uri: lb://bank-api
        predicates:
          # TODO - bank endpoints
          - Path=/bank/**
        filters:
          - TokenRelay=
          - RemoveRequestHeader=Cookie
      - id: dotnet
        uri: lb://IncomeExpensesService
        predicates:
          - Path=/IncomeExpenses/**
        # TODO - security in .net microservice
        filters:
          - TokenRelay=
          - RemoveRequestHeader=Cookie
          