okta:
  oauth2:
    client-secret: lU9hWly4yXWhOeY2JA444U_IubgqSzzDT0hXNp_l
    client-id: 0oa4m4zmhxMRfGz1i5d7
    issuer: https://dev-54064931.okta.com/oauth2/default
    redirect-uri: /login/oauth2/code/okta

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
      httpclient:
        ssl:
          useInsecureTrustManager: true
    routes:
      - id: users
        uri: lb://car-service
        predicates:
          - Path=/cars/**
        filters:
          - TokenRelay=
          - RemoveRequestHeader=Cookie
      - id: dotnet
        uri: lb://IncomeExpensesService
        predicates:
          - Path=/IncomeExpenses/**
          