swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
host: localhost:8081
basePath: /
tags:
  - name: bank-controller
    description: Bank Controller
paths:
  /bank/payment:
    get:
      tags:
        - bank-controller
      summary: paymentList
      operationId: paymentListUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: dateFrom
          in: query
          description: ISO-format - e.g. 2020-01-23T18:25:43.511Z
          required: true
          type: string
        - name: dateTo
          in: query
          description: ISO-format - e.g. 2020-01-23T18:25:43.511Z
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Payment'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /bank/payment/value:
    get:
      tags:
        - bank-controller
      summary: paymentValue
      operationId: paymentValueUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: dateFrom
          in: query
          description: ISO-format - e.g. 2020-01-23T18:25:43.511Z
          required: true
          type: string
        - name: dateTo
          in: query
          description: ISO-format - e.g. 2020-01-23T18:25:43.511Z
          required: true
          type: string
      responses:
        '200':
          description: Summary of payments value
          schema:
            type: number
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /bank/transaction:
    get:
      tags:
        - bank-controller
      summary: transactionList
      operationId: transactionListUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: dateFrom
          in: query
          description: ISO-format - e.g. 2020-01-23T18:25:43.511Z
          required: true
          type: string
        - name: dateTo
          in: query
          description: ISO-format - e.g. 2020-01-23T18:25:43.511Z
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /bank/transaction/value:
    get:
      tags:
        - bank-controller
      summary: transactionsValue
      operationId: transactionsValueUsingGET
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: dateFrom
          in: query
          description: ISO-format - e.g. 2020-01-23T18:25:43.511Z
          required: true
          type: string
        - name: dateTo
          in: query
          description: ISO-format - e.g. 2020-01-23T18:25:43.511Z
          required: true
          type: string
      responses:
        '200':
          description: Summary of transaction value
          schema:
            type: number
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  AdditionalInfo:
    type: object
    properties:
      constantSymbol:
        type: string
      specificSymbol:
        type: string
      variableSymbol:
        type: string
  AdditionalInfoCard:
    type: object
    properties:
      cardNumber:
        type: string
      mcc:
        type: string
      merchantName:
        type: string
  AdditionalInfoDomestic:
    type: object
    properties:
      constantSymbol:
        type: string
      specificSymbol:
        type: string
      variableSymbol:
        type: string
  AdditionalInfoForeign:
    type: object
    properties:
      exchangeRate:
        type: integer
        format: int32
      originalValue:
        $ref: '#/definitions/OriginalValue'
  OriginalValue:
    type: object
    properties:
      amount:
        type: number
      currency:
        type: string
  PartyAccount:
    type: object
    properties:
      accountNumber:
        type: string
      bankCode:
        type: string
      prefix:
        type: string
  Payment:
    type: object
    properties:
      _id:
        type: string
      accountId:
        type: integer
        format: int32
      additionalInfo:
        $ref: '#/definitions/AdditionalInfo'
      dueDate:
        type: string
      editableByUser:
        type: boolean
      partyAccount:
        $ref: '#/definitions/PartyAccount'
      realizationStatus:
        type: string
      recuringPayment:
        $ref: '#/definitions/RecuringPayment'
      value:
        $ref: '#/definitions/Value'
  RecuringPayment:
    type: object
    properties:
      firstPayment:
        type: string
      interval:
        type: string
        enum:
          - YEAR
          - MONTH
          - WEEK
      lastPayment:
        type: string
  Transaction:
    type: object
    properties:
      accountId:
        type: integer
        format: int32
      additionalInfoCard:
        $ref: '#/definitions/AdditionalInfoCard'
      additionalInfoDomestic:
        $ref: '#/definitions/AdditionalInfoDomestic'
      additionalInfoForeign:
        $ref: '#/definitions/AdditionalInfoForeign'
      bookingDate:
        type: string
      categoryId:
        type: integer
        format: int32
      direction:
        type: string
        enum:
          - INCOMING
          - OUTGOING
      id:
        type: string
      partyAccount:
        $ref: '#/definitions/PartyAccount'
      partyDescription:
        type: string
      payeeMessage:
        type: string
      payerMessage:
        type: string
      transactionFee:
        type: integer
        format: int32
      transactionFeeCanceled:
        type: boolean
      transactionType:
        type: string
      userDescription:
        type: string
      value:
        $ref: '#/definitions/Value'
      valueDate:
        type: string
  Value:
    type: object
    properties:
      amount:
        type: number
      currency:
        type: string
